# Generated by Django 2.2.9 on 2020-08-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tipo',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('chofer', 'Chofer')], default='cliente', max_length=20),
        ),
    ]
