# Generated by Django 2.2.9 on 2020-08-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_user_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chofer',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tipo',
        ),
        migrations.AddField(
            model_name='chofer',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cantidad_viajes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
